awesome_events/config/routes.rb
Rails.application.routes.draw do
  root to: 'welcome#index'
  get '/auth/:provider/callback' => 'sessions#create'
  get '/logout' => 'sessions#destroy', as: :logout

  resource :user, only: :destroy do
    get 'retire'
  end

  resources :events, except: :index do
    resources :tickets, only: [ :new, :create, :destroy ]
  end

  match '*path' => 'application#error404', via: :all

end

awesome_events/app/models/event.rb
class Event < ActiveRecord::Base
  # carrierwave settings
  mount_uploader :event_image, EventImageUploader

  belongs_to :owner, class_name: 'User'
  has_many :tickets, dependent: :destroy

  validates :name, length: { maximum: 50 }, presence: true
  validates :place, length: { maximum: 100 }, presence: true
  validates :content, length: { maximum: 2000 }, presence: true
  validates :start_time, presence: true
  validates :end_time, presence: true
  validate :start_time_should_be_before_end_time

  def self.ransackable_attributes(auth_object = nil)
    %w(name start_time)
  end

  def self.ransackable_associations(auth_object = nil)
    []
  end

  def created_by?(user)
    return false unless user
    owner_id == user.id
  end

  def rails?
    !!(name =~ /Rails/)
  end

  private

  def start_time_should_be_before_end_time
    return unless start_time && end_time

    if start_time >= end_time
      errors.add(:start_time, 'は終了時刻よりも前に設定してください')
    end
  end
end

awesome_events/app/models/ticket.rb
class Ticket < ActiveRecord::Base
  belongs_to :user
  belongs_to :event

  validates :comment, length: { maximum: 30 }, allow_blank: true
end

awesome_events/app/models/user.rb
class User < ActiveRecord::Base
  before_destroy :check_all_events_finished

  has_many :created_events, class_name: 'Event', foreign_key: :owner_id, dependent: :nullify
  has_many :tickets, dependent: :nullify
  has_many :participating_events, through: :tickets, source: :event

  # Find or Create from OmniAuth::AuthHash
  #
  # @param auth_hash [OmniAuth::AuthHash]
  # @return user
  def self.find_or_create_from_auth_hash(auth_hash)
    provider  = auth_hash[:provider]
    uid       = auth_hash[:uid]
    nickname  = auth_hash[:info][:nickname]
    image_url = auth_hash[:info][:image]

    User.find_or_create_by(provider: provider, uid: uid) do |user|
      user.nickname = nickname
      user.image_url = image_url
    end
  end

  private

  def check_all_events_finished
    now = Time.current
    if created_events.where(':now < end_time', now: now).exists?
      errors[:base] << '公開中の未終了イベントが存在します'
    end

    if participating_events.where(':now < end_time', now: now).exists?
      errors[:base] << '未終了の参加イベントが存在します'
    end
    errors.blank?
  end
end

awesome_events/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  helper_method :current_user, :logged_in?

  rescue_from Exception, with: :error500
  rescue_from ActiveRecord::RecordNotFound, ActionController::RoutingError, with: :error404

  private

  def current_user
    return unless session[:user_id]
    @current_user ||= User.find(session[:user_id])
  end

  def logged_in?
    !!session[:user_id]
  end

  def authenticate
    return if logged_in?
    redirect_to root_path, alert: 'ログインしてください'
  end

  def error404(e)
    render 'error404', status: 404, formats: [:html]
  end

  def error500(e)
    logger.error [e, *e.backtrace].join("\n")
    render 'error500', status: 500, formats: [:html]
  end
end

awesome_events/app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :authenticate, except: :show

  def new
    @event = current_user.created_events.build
  end

  def create
    @event = current_user.created_events.build(event_params)
    if @event.save
      redirect_to @event, notice: '作成しました'
    else
      render :new
    end
  end

  def show
    @event = Event.find(params[:id])
    @ticket = current_user && current_user.tickets.find_by(event_id: params[:id])
    @tickets = @event.tickets.includes(:user).order(:created_at)
  end

  def edit
    @event = current_user.created_events.find(params[:id])
  end

  def update
    @event = current_user.created_events.find(params[:id])
    if @event.update(event_params)
      redirect_to @event, notice: '更新しました'
    else
      render :edit
    end
  end

  def destroy
    @event = current_user.created_events.find(params[:id])
    @event.destroy!
    redirect_to root_path, notice: '削除しました'
  end

  private

  def event_params
    params.require(:event).permit(
      :name, :place, :event_image, :event_image_cache,
      :remove_event_image, :content, :start_time, :end_time
    )
  end
end

awesome_events/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  # get '/auth/:provider/callback'
  def create
    user = User.find_or_create_from_auth_hash(request.env['omniauth.auth'])
    session[:user_id] = user.id
    redirect_to root_path, notice: 'ログインしました'
  end

  # get '/logout'
  def destroy
    reset_session
    redirect_to root_path, notice: 'ログアウトしました'
  end
end

awesome_events/app/controllers/tickets_controller.rb
class TicketsController < ApplicationController
  before_action :authenticate

  def new
    raise ActionController::RoutingError, 'ログイン状態で TicketsController#new にアクセス'
  end

  # @note
  #   フォームの remote: true でリクエストされる想定なので
  #   失敗時にはエラーメッセージを json で返す
  def create
    ticket = current_user.tickets.build do |t|
      t.event_id = params[:event_id]
      t.comment = params[:ticket][:comment]
    end
    if ticket.save
      flash[:notice] = 'このイベントに参加表明しました'
      head 201
    else
      render json: { messages: ticket.errors.full_messages }, status: 422
    end
  end

  def destroy
    ticket = current_user.tickets.find_by!(event_id: params[:event_id])
    ticket.destroy!
    redirect_to event_path(params[:event_id]), notice: 'このイベントへの参加をキャンセルしました'
  end
end

awesome_events/app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate

  def retire
  end

  def destroy
    if current_user.destroy
      reset_session
      redirect_to root_path, notice: '退会完了しました'
    else
      render :retire
    end
  end
end

awesome_events/app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  PER = 3

  def index
    @q = Event.page(params[:page]).per(PER).order(:start_time).search(search_params)

    @events = @q.result(distinct: true)
  end

  private

  def search_params
    params.require(:q).permit(:name_cont, :start_time_gteq)
  rescue
    { start_time_gteq: Time.current }
  end
end

awesome_events/app/helpers/application_helper.rb
module ApplicationHelper
  def url_for_twitter(user)
    "https://twitter.com/#{user.nickname}"
  end
end

awesome_events/app/helpers/events_helper.rb
module EventsHelper
end

awesome_events/app/helpers/sessions_helper.rb
module SessionsHelper
end

awesome_events/app/helpers/tickets_helper.rb
module TicketsHelper
end

awesome_events/app/helpers/users_helper.rb
module UsersHelper
end

awesome_events/app/helpers/welcome_helper.rb
module WelcomeHelper
end

awesome_events/app/views/application/error404.html.erb
ご指定になったページは存在しません

awesome_events/app/views/application/error500.html.erb
エラーが発生しました

awesome_events/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>AwesomeEvents</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <header class="navbar navbar-default" role="navigation">
    <div class="container">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <%= link_to 'AwesomeEvents', root_path, class: 'navbar-brand' %>
      </div>
      <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
        <ul class="nav navbar-nav navbar-right">
          <li><%= link_to 'イベントを作る', new_event_path %></li>
          <% if logged_in? %>
            <li><%= link_to '退会', retire_user_path %></li>
            <li><%= link_to 'ログアウト', logout_path %></li>
          <% else %>
            <li><%= link_to 'Twitter でログイン', '/auth/twitter' %></li>
          <% end %>
        </ul>
      </div>
    </div>
  </header>
  <div class="container">
    <% if flash[:notice] %>
      <div class="alert alert-success">
        <%= flash[:notice] %>
      </div>
    <% end %>
    <% if flash[:alert] %>
      <div class="alert alert-danger">
        <%= flash[:alert] %>
      </div>
    <% end %>
    <%= yield %>
  </div>
</body>
</html>

awesome_events/app/views/welcome/index.html.erb
<% now = Time.current %>

<div class="page-header">
  <h1>イベント一覧</h1>
</div>

<%= search_form_for(@q, url: root_path, class: 'well') do |f| %>
  <div class="form-group">
    <%= f.label :name_cont, 'イベント名' %>
    <%= f.text_field :name_cont, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :start_time_gteq, '開催日' %>
    <div>
      <%= f.date_select :start_time_gteq, start_year: 2015, end_year: now.year + 1, prompt: true %> 〜
    </div>
  </div>
  <%= f.submit '検索', class: 'btn btn-default' %>
<% end %>

<div class="list-group">
  <% @events.each do |event| %>
    <%= link_to(event, class: 'list-group-item') do %>
      <h4 class="list-group-item-heading">
        <%= event.name %>
      </h4>
      <p class="list-group-item-text">
        <%= event.start_time.strftime('%Y/%m/%d %H:%M') %> - <%= event.end_time.strftime('%Y/%m/%d %H:%M') %>
      </p>
    <% end %>
  <% end %>
  <%= paginate @events %>
</div>